{{- $needGameSecret := not .Values.gameServer.existingSecret -}}
{{- $needPlusSecret := and .Values.windrosePlus.enabled (not .Values.windrosePlus.existingSecret) -}}
{{- if or $needGameSecret $needPlusSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "windrose-k8s.fullname" . }}
  labels:
    {{- include "windrose-k8s.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $needGameSecret }}
  server-password: {{ default (randAlphaNum 12) .Values.gameServer.password | b64enc | quote }}
  {{- end }}
  {{- if $needPlusSecret }}
  windrose-plus-rcon-password: {{ default (randAlphaNum 16) .Values.windrosePlus.rconPassword | b64enc | quote }}
  {{- end }}
{{- end }}
